// app/layout.tsx (yoki app/layout.jsx)

import "./globals.css";
import { Poppins } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import Provider from "./provider";

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap", 
  variable: "--font-poppins",
});


const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bebas", 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${bebas.variable}`}>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
